{"uuid": "d0cee644-1c21-4274-952c-b7ea270cce32", "children": ["89501faa-478f-40ff-9f9c-b42d01d0254b", "c1527431-71e5-4a38-ae22-aaec6b789053"], "befores": [{"name": "record", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [WinError 2] 系统找不到指定的文件。\n", "trace": "  File \"c:\\testtools\\python\\python37\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\testtools\\python\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\testtools\\python\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"C:\\Users\\heli\\PycharmProjects\\diy_appium\\scripts\\conftest.py\", line 19, in record\n    p = subprocess.Popen(cmd, shell=False, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)\n  File \"c:\\testtools\\python\\python37\\lib\\subprocess.py\", line 800, in __init__\n    restore_signals, start_new_session)\n  File \"c:\\testtools\\python\\python37\\lib\\subprocess.py\", line 1207, in _execute_child\n    startupinfo)\n"}, "start": 1592382127663, "stop": 1592382127670}], "start": 1592382127663, "stop": 1592382127787}