{"uuid": "16005260-014d-4bed-b3fa-ae46da7835f4", "children": ["617c3dbc-c7ec-4a66-9808-2cd594e34e85", "841b9e70-ea53-4f54-8380-50741afe73aa"], "befores": [{"name": "record", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [WinError 2] 系统找不到指定的文件。\n", "trace": "  File \"c:\\testtools\\python\\python37\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\testtools\\python\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\testtools\\python\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"C:\\Users\\heli\\PycharmProjects\\diy_appium\\scripts\\conftest.py\", line 20, in record\n    p = subprocess.Popen(cmd, shell=False, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)\n  File \"c:\\testtools\\python\\python37\\lib\\subprocess.py\", line 800, in __init__\n    restore_signals, start_new_session)\n  File \"c:\\testtools\\python\\python37\\lib\\subprocess.py\", line 1207, in _execute_child\n    startupinfo)\n"}, "start": 1592385727209, "stop": 1592385727218}], "start": 1592385727209, "stop": 1592385727331}