{"uuid": "0dbc8773-4d33-4f97-a6c3-08c79205d226", "children": ["3a9d5c15-98e7-4b97-942a-0b301c53978f", "19b9a9b1-a1c8-4fa1-9cf9-2177418d112d"], "befores": [{"name": "record", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [WinError 2] 系统找不到指定的文件。\n", "trace": "  File \"c:\\testtools\\python\\python37\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\testtools\\python\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\testtools\\python\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"C:\\Users\\heli\\PycharmProjects\\diy_appium\\scripts\\conftest.py\", line 19, in record\n    p = subprocess.Popen(cmd, shell=False, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)\n  File \"c:\\testtools\\python\\python37\\lib\\subprocess.py\", line 800, in __init__\n    restore_signals, start_new_session)\n  File \"c:\\testtools\\python\\python37\\lib\\subprocess.py\", line 1207, in _execute_child\n    startupinfo)\n"}, "start": 1592383789457, "stop": 1592383789464}], "start": 1592383789457, "stop": 1592383789571}